version: "3.3"
services: 
  nginx:
    build: app
    ports: 
      - 80:80
      - 443:443
    environment: 
      PORT: 80
      NODE_ENV: development
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: example
  account:
    build: account
    environment: 
      NODE_ENV: development
      volumes:
       - ./account/src:/app/src