version: "3.3"
services: 
  nginx:
    build: app
    ports: 
      - 80:80
      - 443:443
    environment: 
      PORT: 80
      DEPLOY_ENV: development
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: example
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  account:
    build: account
    environment: 
      NODE_ENV: development
    volumes:
      - ./account/src:/app/src
  billing:
    build: billing
    environment: 
      NODE_ENV: development
    volumes:
      - ./billing/src:/app/src
