version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: localkafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  consumer:
    build: consumer
    depends_on: 
      - kafka
  producer:
    build: producer
    depends_on: 
      - consumer
      - kafka
