version: "2"
services:
  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - "29092:29092"
      - "9092:9092"
      - "29093:29093"
      - "9093:9093"
      - "29094:29094"
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # https://github.com/wurstmeister/kafka-docker#automatically-create-topics
      KAFKA_CREATE_TOPICS: "logs:1:3"
  consumer:
    build: consumer
    depends_on:
      - kafka
  producer:
    build: producer
    depends_on:
      - consumer
      - kafka
